import Head from 'next/head';
import AuthButton from '../components/auth-button';
import styles from '../styles/Home.module.css';
import Navbar from '../components/navbar';
import prisma from '../prisma/prisma';
export async function getServerSideProps() {
  const classrooms = await prisma.Classroom.findMany();
  const output = [];
  for (let i = 0; i < classrooms.length; i++) {
    output[i] = {
      classroomName: classrooms[i].classroomName,
      classroomId: classrooms[i].classroomId,
      description: classrooms[i].description,
      createdAt: JSON.stringify(classrooms[i].createdAt)
    };
  }
  return {
    props: { classrooms: output }
  };
}

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
          <Navbar></Navbar>
        </Head>
        <div className='mt-20'>
          <h1 className='text-[40px] font-bold text-center big-heading '>
            Welcome Teachers!
          </h1>
        </div>
      </div>
      <div className='mt-20 text-center border-4 border-[#0a0a23] bg-white p-10 rounded-lg shadow-xl max-w-2xl mx-auto'>
        <h1 className='text-2xl font-bold'>Sign In</h1>
        <div className='mt-4 mb-10'>
          <p className='text-gray-600'>
            Please sign in to access Classroom Dashboard Mode
          </p>
        </div>
        <AuthButton></AuthButton>
      </div>
      <div className='mt-20 text-center border-4 border-[#0a0a23] bg-white p-10 rounded-lg shadow-xl max-w-2xl mx-auto'>
        <h1 className='text-2xl font-bold'>About</h1>
        <div className={'p-6'}>
          <h1
            className={
              'box-content bg-[#d0d0d5] h-100 w-100 p-4 border-4 border-[#0a0a23] text-s'
            }
          >
            A self-hosted solution to help teachers plan and manage
            classroom-based learning, on top of freeCodeCamp&apos;s learn
            platform.
          </h1>
        </div>
      </div>
    </>
  );
}
